name: Run Flask Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t flask-app .

    - name: Run tests inside Docker
      run: docker run --rm flask-app pytest